//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIdentity {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMy() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyIdentity.ResourceMy", typeof(ResourceMy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p style=&quot;color:red&quot;&gt;
        ///    Спасибо за регистрацию&lt;br&gt;
        ///    Подтверждение пароля выслано Вам на почту.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string good_registration {
            get {
                return ResourceManager.GetString("good_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAH3ElEQVR4nO2be2wcRxnAf3N7Pl/9SBObYEFTEkgqQAVSQfJHWqKqqSpR8hAPCYGKIpCKlBYk1CLhhKgokIgkKlQpSFGCKqSqUgWRC8hJKY8S1+VRHgGlKUnapJHtyiaxffY9vPbu7c7O8MfZF9/5Hrt7d8bQ/KSVfDvzzcz37TfffDO7hhvc4G2NqFQ4ODi4FTimtV61SOMJhRBiGNi1Zs2a54PKRqqUL3nlAWbHeCyMbEUD/C8oP0fYsVbzgP97KsaAgYEBXXMHqRTeyy9jj4/jOU7Fuu0PPVTy/umBNHv7hrlmurUOZxitdnHks/lYEQ0i/difJgDYf1enr/oincbs6UG5tQ28TsoDrEKI40B+ujR0Cnj9/TUrD9RL+Ryuc8v8n4E8wO+Tn8MeH69YHo3HaV2+nJ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css&quot;&gt;
        ///&lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.0-preview.2.20167.3/signalr.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;div data-ion100=&quot;100&quot; class=&quot;container&quot;&gt;
        ///    &lt;h2&gt;Modal Example&lt;/h2&gt;
        ///    &lt;!-- Trigger the modal with [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div&gt;
        ///    &lt;div class=&quot;alert alert-danger&quot; style=&quot;visibility: collapse&quot; role=&quot;alert&quot; id=&quot;error_message&quot;&gt;
        ///       
        ///    &lt;/div&gt;
        ///   
        ///    &lt;div class=&quot;form-group row&quot;&gt;
        ///        &lt;div class=&quot;col-sm-10&quot;&gt;
        ///            &lt;input type=&quot;email&quot; class=&quot;form-control&quot; id=&quot;email&quot; placeholder=&quot;Email&quot;&gt;
        ///            &lt;span style=&quot;padding-left: 5px&quot; id=&apos;result&apos;&gt;&lt;/span&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;form-group row&quot;&gt;
        ///        &lt;div class=&quot;col-sm-10&quot;&gt;
        ///            &lt;input type=&quot;password&quot; class=&quot;form-control&quot; id=&quot;passwor [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string login1 {
            get {
                return ResourceManager.GetString("login1", resourceCulture);
            }
        }
    }
}
